[package]
name = "evolve"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
log = "0.4.22"
rand = "0.8.5"
statrs = "0.17.1"

[dev-dependencies]
bitvec = "1.0.1"
env_logger = "0.11.5"
