# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  push:
    branches:
      - master

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Build the One Max Problem example"
        run: cargo build --release --example one_max_problem

      - uses: bencherdev/bencher@main
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project evolve \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch master \
          --testbed ubuntu-latest \
          --adapter json \
          --err \
          "./target/release/examples/one_max_problem"
